// Auto-generated by scripts/update_feed.js
window.FEED_UPDATES = [
  {
    "id": "din1pM12Alg",
    "title": "Monòlegs km0 (85.7) Santoral 16/01, IA del dia, Barça, Julio Iglesias, el Prat i la Corina Machado!",
    "thumbnail": "https://i.ytimg.com/vi/din1pM12Alg/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-16T08:36:28Z",
    "categories": [
      "humor",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "5U0vnOsxIhs",
    "title": "ERC fa negoci amb el drama humà dels menors d'edat custodiats per la Generalitat /2026 01 15",
    "thumbnail": "https://i.ytimg.com/vi/5U0vnOsxIhs/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-15T21:53:15Z",
    "categories": [
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "TKUR9sOyF60",
    "title": "Monòlegs km0 (84.7) Santoral, IA del dia, pluges, dents, Julio, Madrid i Barça i les tovalloles! 💩💩💩",
    "thumbnail": "https://i.ytimg.com/vi/TKUR9sOyF60/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-15T08:41:17Z",
    "categories": [
      "humor",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "eUyRCgOWaPc",
    "title": "El fill gran de Jordi Pujol no cobrava com a intermediari sinó com una altra cosa /2026 01 14",
    "thumbnail": "https://i.ytimg.com/vi/eUyRCgOWaPc/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-14T21:59:11Z",
    "categories": [
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "sZoYVpX1QHo",
    "title": "Monòlegs km0 (83.7) Santoral 14/01, IA, canvi climàtic, reunió, USTEC, V-16, Trump i osteoporosi! 💩",
    "thumbnail": "https://i.ytimg.com/vi/sZoYVpX1QHo/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-14T08:46:11Z",
    "categories": [
      "humor",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "C44VS3k00E4",
    "title": "Amb publicitat i subvencions Catalunya té els mitjans de comunicació d'una dictadura /2026 01 13",
    "thumbnail": "https://i.ytimg.com/vi/C44VS3k00E4/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-13T22:14:52Z",
    "categories": [
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "udnve6TqYEM",
    "title": "Catalans sense fronteres: Itàlia. Dia 43 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/udnve6TqYEM/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-13T16:01:25Z",
    "categories": [
      "vida"
    ],
    "isShort": false
  },
  {
    "id": "SqHN01ixMxE",
    "title": "🦙 LLAMA LLAMA - Com s'hi juga? [tutorial]",
    "thumbnail": "https://i.ytimg.com/vi/SqHN01ixMxE/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-13T11:01:01Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "isShort": false
  },
  {
    "id": "COZ1wDRntxU",
    "title": "Monòlegs km0 (82.7) Santoral 13/01, el Madrid fa fora Xabi Alonso i altres merdes! 💩💩💩 #pqeam",
    "thumbnail": "https://i.ytimg.com/vi/COZ1wDRntxU/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-13T08:53:59Z",
    "categories": [
      "humor",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "JkAk5rPi8lY",
    "title": "Els nostres pagesos, atrapats entre la traïció de la UE i la indiferència general /2026 01 12",
    "thumbnail": "https://i.ytimg.com/vi/JkAk5rPi8lY/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-12T21:56:06Z",
    "categories": [
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "L9lOghuO_S0",
    "title": "Acampo a -3 °C. Dia 42 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/L9lOghuO_S0/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-12T14:51:12Z",
    "categories": [
      "vida"
    ],
    "isShort": false
  },
  {
    "id": "yM_RZg9jlx4",
    "title": "Monòlegs km0 (81.7) Santoral 12/01, IA del dia, Barça campió!, forn, Cantó, xarampió i galàxia! 💩💩💩",
    "thumbnail": "https://i.ytimg.com/vi/yM_RZg9jlx4/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-12T09:39:25Z",
    "categories": [
      "humor",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "AeoqjHYUn9s",
    "title": "Fred al Piemonte. Dia 41 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/AeoqjHYUn9s/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-10T20:09:02Z",
    "categories": [
      "vida"
    ],
    "isShort": false
  },
  {
    "id": "ZdWqLoKRE28",
    "title": "Etapa Reina...? Dia 40 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/ZdWqLoKRE28/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-09T19:59:38Z",
    "categories": [
      "vida"
    ],
    "isShort": false
  },
  {
    "id": "ws8iWa71Wx4",
    "title": "Oriol Junqueras consolida amb Pedro Sánchez l'espoli fiscal de Catalunya /2026 01 09",
    "thumbnail": "https://i.ytimg.com/vi/ws8iWa71Wx4/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-09T08:25:51Z",
    "categories": [
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "6iq4ZWx52qo",
    "title": "Tancat per dol. Dia 39 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/6iq4ZWx52qo/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-08T21:46:37Z",
    "categories": [
      "vida"
    ],
    "isShort": false
  },
  {
    "id": "jm9l5dxCLpE",
    "title": "📰 TOP 10 de 2025 (el top dels jocs que xirrien): Els nostres jocs de 2025",
    "thumbnail": "https://i.ytimg.com/vi/jm9l5dxCLpE/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-08T11:01:33Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "isShort": false
  },
  {
    "id": "FLR3gEYe3cs",
    "title": "🏰 EMBLEMS - Com s'hi juga? [tutorial]",
    "thumbnail": "https://i.ytimg.com/vi/FLR3gEYe3cs/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-02T11:00:37Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "isShort": false
  },
  {
    "id": "Ny6PGqLx79Q",
    "title": "ESPECIAL RESUM DE L'ANY | Us donem la turra del 2025 + TOP",
    "thumbnail": "https://i.ytimg.com/vi/Ny6PGqLx79Q/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2025-12-30T20:29:37Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "isShort": false
  },
  {
    "id": "khGLrE5ZA4M",
    "title": "🎲 CARNIVAL OF SINS - Com s'hi juga? [tutorial]",
    "thumbnail": "https://i.ytimg.com/vi/khGLrE5ZA4M/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2025-12-30T11:01:32Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "isShort": false
  },
  {
    "id": "Fg0u3SNOF-E",
    "title": "Amb Xavier Gual, Educació i Immigració, Escriptor i professor de secundària, Aula d'acollida,",
    "thumbnail": "https://i.ytimg.com/vi/Fg0u3SNOF-E/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-12-28T12:10:10Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "6-lokvEXno8",
    "title": "Amb Júlia Ojeda, Pactaríeu amb QUALSEVOL partit independentista? Manuel de Pedrolo, Prosa de combat",
    "thumbnail": "https://i.ytimg.com/vi/6-lokvEXno8/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-12-20T09:45:58Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "W7Yd5FBU0Zk",
    "title": "Vull trobar feina | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/W7Yd5FBU0Zk/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-19T09:33:22Z",
    "categories": [
      "humor"
    ],
    "isShort": false
  },
  {
    "id": "5naWPM9DZoA",
    "title": "influmerder | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/5naWPM9DZoA/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-18T16:37:49Z",
    "categories": [
      "humor"
    ],
    "isShort": false
  },
  {
    "id": "w-_h2C_ka3c",
    "title": "Temporada 4 | #Esquetxes comèdia en #català (Tots els vídeos de 2025)",
    "thumbnail": "https://i.ytimg.com/vi/w-_h2C_ka3c/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-17T02:08:25Z",
    "categories": [
      "humor"
    ],
    "isShort": false
  },
  {
    "id": "TSanPHDdyys",
    "title": "La bestiola (La casa Nostromo: Hi ha una bestiola al lavabo) | #Esquetxes #comèdia en #català T4",
    "thumbnail": "https://i.ytimg.com/vi/TSanPHDdyys/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-15T20:20:58Z",
    "categories": [
      "humor"
    ],
    "isShort": false
  },
  {
    "id": "JMsG6zAfBPg",
    "title": "Trailer Temporada 4 | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/JMsG6zAfBPg/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-05T21:03:37Z",
    "categories": [
      "humor"
    ],
    "isShort": false
  },
  {
    "id": "MqyJ9GqJhaw",
    "title": "Amb Els ODIOSOS VUIT, L'actriu que ens té el cor robat és..De l'amor a l'odi xls ÒSCARS!L'Escaquimat",
    "thumbnail": "https://i.ytimg.com/vi/MqyJ9GqJhaw/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-11-02T12:44:16Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "mhUp3bTpZNQ",
    "title": "Amb Miquel Bonet, Els votants d'Aliança Catalana saben això? Periodisme de contacte, Difamació",
    "thumbnail": "https://i.ytimg.com/vi/mhUp3bTpZNQ/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-10-19T10:54:43Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "isShort": false
  },
  {
    "id": "fgZbjjp87Xg",
    "title": "Amb Xavier Rius_GEN0CIDI o GU3RRA? Palestina, Israel, extrema dreta, woke, jueus, L'EscaQuimat",
    "thumbnail": "https://i.ytimg.com/vi/fgZbjjp87Xg/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-10-03T09:42:16Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "isShort": false
  }
];
